### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by QiangZiBro** [kong36088/BaiduImageSpider#8]
错误内容：*UnboundLocalError: local variable 'page' referenced before assignment*
```
<urlopen error unknown url type: socks5>
-----urlErrorurl: http://image.baidu.com/search/avatarjson?tn=resultjsonavatarnew&ie=utf-8&word=%E5%9C%9F%E5%A3%A4&cg=girl&pn=0&rn=60&itg=0&z=0&fr=&width=&height=&lm=-1&ic=0&s=0&st=-1&gsm=1e0000001e
Traceback (most recent call last):
  File "index.py", line 135, in <module>
    crawler.start('土壤', 1, 1)  # 抓取关键词为 “二次元 美女”，总数为 10 页（即总共 10*60=600 张），起始抓取的页码为 1
  File "index.py", line 128, in start
    self.get_images(word)
  File "index.py", line 114, in get_images
    page.close()
UnboundLocalError: local variable 'page' referenced before assignment

```

**Comment by kong36088** [comment]
从报错来看是因为你的PC上开启了代理，请关闭代理后再重试一遍
